permalink: /blog/:year-:month-:day-:title
title: solenopsis
url: http://solenopsis.org/blog

auto: true

parent:
     name: solenopsis.org
     url: http://solenopsis.org

feedurl: http://solenopsis.org/blog/atom.xml
sourceurl: http://github.com/solenopsis/blog/

markdown: kramdown

author:
     name: solenopsis
     email: solenopsis@deadlypenguin.com
     twitter: https://twitter.com/sfdcsolenopsis